### ISSUE TITLE
There might be an issue with oParagraph.Search

### ISSUE THREAD

**Issue by nicewillsuccess** [ONLYOFFICE/DocumentBuilder#130]
I'm encountering an issue while using the oParagraph.Search method. When I attempt to bold the entire search result (e.g., "text"), only part of the text, like "tex," is getting bolded instead of the full "text" as I expected.

**Comment by nicewillsuccess** [comment]
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(2);
var aSearch = oParagraph.Search("text");
aSearch[0].SetBold(true);

**Comment by askonev** [comment]
@nicewillsuccess `bug 66725` has been fixed on version 8.1

**Comment by Rita-Bubnova** [comment]
Version 8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by nicewillsuccess** [comment]
> 版本 8.1.1 已发布，因此我关闭了此问题。如果您有更多问题，请随时发表评论或重新打开它。

I tried with the new version, but the issue persists. If a line break is added and then oParagraph.Search is used, it will select the line break, and the last text of the search won’t be included. If Delete() is called at this point, it will also delete the line break.

**Comment by Rita-Bubnova** [comment]
@askonev, Please take a look.

**Comment by nicewillsuccess** [comment]
var oParagraphLineBreak = oDocument.GetElement( 2);
var oRun = Api.CreateRun();
oRun.AddLineBreak();
oParagraphLineBreak.AddElement(oRun);
oRun = Api.CreateRun();
oRun.AddText("hello");
oRun.SetFontSize(32);
oRun.SetShd("clear", 240, 230, 140);
var oSearch = oParagraphLineBreak.Search("hello");
oSearch[0].Delete();
This is part of the code. I first added a line break, then added the text 'hello'. When using the Search method to find 'hello', the text returned by Search is '\rhell' instead of 'hello'. When calling Delete, it removes both the line break and 'hell'. @askonev

**Comment by nicewillsuccess** [comment]
Hello, has this issue been resolved? @Rita-Bubnova

**Comment by askonev** [comment]
The problems described in the issue have been fixed on version 8.2.0

**Comment by Rita-Bubnova** [comment]
DocumentBuilder v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
